###
POST http://localhost:8080/dolphin/v1/query/execute
Content-Type: application/json

{
  "query": "select * from test.s_test1.test2 a join test2.s_test3.test6 b on a.year = b.ptime limit 10"
}

###
POST http://localhost:8080/dolphin/v1/query/execute
Content-Type: application/json

{
  "query": "select * from test_table1 a join test_table2 b on a.year = b.ptime limit 10"
}

###
GET http://localhost:8080/dolphin/v1/query/status/7078cbcd-16ad-4573-880f-af43e9157494


###
GET http://localhost:8080/dolphin/v1/query/read/7078cbcd-16ad-4573-880f-af43e9157494

###
GET http://localhost:8080/dolphin/v1/query/download/7078cbcd-16ad-4573-880f-af43e9157494


###
POST http://localhost:8080/dolphin/v1/query/execute
Content-Type: application/json

{
  "query": "select * from (select a.b.c.d from aa.`aa` left  join test1) as likse"
}

###
POST http://localhost:8080/dolphin/v1/query/execute
Content-Type: application/json

{
  "query": "select * from  aa.`aa`"
}


###
GET http://localhost:8080/dolphin/v1/query/status/7078cbcd-16ad-4573-880f-af43e9157494

###
GET http://localhost:8080/dolphin/v1/query/status/70adsf

###
POST localhost:8080/dolphin/open-metadata/notify
Content-Type: application/json

{
  "id": "caaf9e59-8e9c-4531-9a72-7d070ef0b5b5",
  "eventType": "entityCreated",
  "entityType": "databaseService",
  "entityId": "8d30dd9d-bdde-4b9a-b4e0-b790501df0d8",
  "previousVersion": 0.1,
  "currentVersion": 0.1,
  "userName": "admin",
  "timestamp": 1717482789023,
  "entity": "{\"id\":\"8d30dd9d-bdde-4b9a-b4e0-b790501df0d8\",\"name\":\"fwani-maria\",\"fullyQualifiedName\":\"fwani-maria\",\"serviceType\":\"MariaDB\",\"description\":\"\",\"connection\":{},\"version\":0.1,\"updatedAt\":1717482789023,\"updatedBy\":\"admin\",\"owner\":{\"id\":\"a58ea22d-109f-4a19-8146-4af0feb1be33\",\"type\":\"user\",\"name\":\"admin\",\"fullyQualifiedName\":\"admin\",\"deleted\":false,\"href\":\"http://192.168.106.104:8585/api/v1/users/a58ea22d-109f-4a19-8146-4af0feb1be33\"},\"href\":\"http://192.168.106.104:8585/api/v1/services/databaseServices/206e4a34-3fb3-4995-817b-9503ac3aecc1\",\"deleted\":false}"
}


###
POST localhost:8080/dolphin/open-metadata/notify
Content-Type: application/json

{
  "id": "8c84f7e5-f168-45e7-a1c3-bea3fa55ea73",
  "eventType": "entityCreated",
  "entityType": "storageService",
  "entityId": "e2490763-d740-421b-b6f2-0f80c83011d8",
  "previousVersion": 0.1,
  "currentVersion": 0.1,
  "userName": "admin",
  "timestamp": 1718171118698,
  "entity": "{\"id\":\"e2490763-d740-421b-b6f2-0f80c83011d8\",\"name\":\"s3-test-trino\",\"fullyQualifiedName\":\"s3-test-trino\",\"serviceType\":\"S3\",\"description\":\"\",\"connection\":{},\"version\":0.1,\"updatedAt\":1718171118698,\"updatedBy\":\"admin\",\"href\":\"http://192.168.106.104:8585/api/v1/services/storageServices/e2490763-d740-421b-b6f2-0f80c83011d8\",\"owner\":{\"id\":\"a58ea22d-109f-4a19-8146-4af0feb1be33\",\"type\":\"user\",\"name\":\"admin\",\"fullyQualifiedName\":\"admin\",\"deleted\":false,\"href\":\"http://192.168.106.104:8585/api/v1/users/a58ea22d-109f-4a19-8146-4af0feb1be33\"},\"deleted\":false}"
}

###
#{
#  "query": "select count(*) from dm_acc_info join dm_acc_main_code on dm_acc_info.acc_type = dm_acc_main_code.acc_type",
#  "referenceModels": [
#    {
#      "fullyQualifiedName": "Fabric-Sample.datafabric.public.dt_dataset",
#      "name": "dt_dataset"
#    },
#    {
#      "fullyQualifiedName": "Fabric-Sample.datafabric.public.spatial_ref_sys",
#      "name": "spatial_ref_sys"
#    },
#    {
#      "fullyQualifiedName": "Fabric-Sample.datafabric.public.dm_acc_info",
#      "name": "dm_acc_info"
#    },
#    {
#      "fullyQualifiedName": "Fabric-Sample.datafabric.public.dm_acc_main_code",
#      "name": "dm_acc_main_code"
#    }
#  ]
#}
###

POST http://{{host}}:{{port}}/dolphin/v1/model
Content-Type: application/json

{
  "modelName": "jb_test_model",
  "displayName": "JB Test Model",
  "description": "This is test model(can use markdown format) by jblim",
  "tags": [
    "ovp_category.550e8400-e29b-41d4-a716-446655440000"
  ],
  "baseModel": {
    "type": "QUERY",
    "query": "select * from `건강보험심사평가원_계절성질환(한랭_및_온열질환)_진료비_통계`",
    "referenceModels": [
      {
        "name": "건강보험심사평가원_계절성질환(한랭_및_온열질환)_진료비_통계",
        "fullyQualifiedName": "MySQL.default.datafabric.건강보험심사평가원_계절성질환(한랭_및_온열질환)_진료비_통계"
      }
    ]
  }
}

###
###

POST http://{{host}}:{{port}}/dolphin/v1/model
Content-Type: application/json

{
  "modelName": "jb_test_model3",
  "displayName": "JB Test Model3",
  "description": "This is test model(can use markdown format) by jblim3",
  "tags": [
    "ovp_category.550e8400-e29b-41d4-a716-446655440000"
  ],
  "baseModel": {
    "type": "QUERY",
    "query": "select * from `준범`",
    "referenceModels": [
      {
        "name": "준범",
        "fullyQualifiedName": "jb-test.datafabric.datafabric.준범"
      }
    ]
  }
}

###

